### ISSUE TITLE
Maybe you can use prestashop-dev-tools 4.x

### ISSUE THREAD

**Issue by SebSept** [okom3pom/hideprestashopcolumns#2]
It may have better support for error detection for this errors 
https://github.com/okom3pom/hideprestashopcolumns/blob/db926830c28f431490666cf762fc852f340640b9/tests/phpstan/phpstan.neon#L28

**Comment by SebSept** [comment]
I don't know but this is just to let know that there is a version 4 of prestashop-dev-tools
I use it in https://github.com/sebsept/ps_dev_base and tha's fine.

**Comment by okom3pom** [comment]
Thank you @SebSept it's my first repo with test :)
For the moment i don't run php stan i have an error and it's impossible to escape this error ...
'#Return typehint of method ModuleCore::getInstanceByName() has invalid type Module.#'
I tryed a lot of ways ... but hes don't work.
I go try with the new version.

**Comment by okom3pom** [comment]
Thank you again @SebSept  https://github.com/okom3pom/hideprestashopcolumns/blob/symfony-controller/tests/phpstan/phpstan.neon
